// <auto-generated />
using Matrix.EmojiTracker.Persist;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Matrix.EmojiTracker.Persist.Migrations
{
    [DbContext(typeof(WorkerDb))]
    [Migration("20190518215806_CreateEmojiCounts")]
    partial class CreateEmojiCounts
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Matrix.EmojiTracker.Database.WorkerModels.EmojiCount", b =>
                {
                    b.Property<string>("Emoji")
                        .HasColumnName("emoji");

                    b.Property<string>("Source")
                        .HasColumnName("source");

                    b.Property<long>("Count")
                        .HasColumnName("count");

                    b.HasKey("Emoji", "Source");

                    b.ToTable("emoji_count");
                });
#pragma warning restore 612, 618
        }
    }
}
